#!/bin/sh

TARGET_DIR=/data/backup/
BACKUP_DIR=/bk
LOGFILE=/data/backup/logs/backup.log

RSYNC=/usr/bin/rsync
RSYNCOPT="-av --delete --bwlimit=62500"

DATE=`date +%u`

echo "`/bin/date` : rsync start." > $LOGFILE

if [ ! -d $BACKUP_DIR/cbag_${DATE} ]
then
 echo "No directory."
 echo "NOTICE: /bk is not mounted." | logger
 exit 1
fi

$RSYNC $RSYNCOPT $TARGET_DIR $BACKUP_DIR/dir_${DATE} >> $LOGFILE

echo "`/bin/date` : rsync end." >> $LOGFILE
echo "===========================" >> $LOGFILE

exit 0
