#!/bin/sh

# コマンド
TAR=/bin/tar
RM=/bin/rm

# ログファイル名
LOGFILES=('access_log' 'error_log')

# 対象ディレクトリ
DIR=/data/logs/

# 処理対象年月
DATE=`date +%Y%m -d '1 month ago'`

# コマンドの存在確認
if [ ! -e ${TAR} -o ! -e ${RM} ]
then
 echo "tar or rm command not found." | logger
 exit 1
fi

# 圧縮・削除
cd ${DIR}
for file in "${LOGFILES[@]}"
do
 ${TAR} zcpf ${file}.${DATE}.tgz ${file}.${DATE}??

 res=$?

 if [ ${res} -eq 0 -a -e ${file}.${DATE}.tgz ]
 then
  ${RM} -f ${file}.${DATE}??
 fi
done

exit 0
